[2023-12-03T00:07:30.894+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_transfer_s3_to_redshift scheduled__2023-12-02T00:00:00+00:00 [queued]>
[2023-12-03T00:07:30.902+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_transfer_s3_to_redshift scheduled__2023-12-02T00:00:00+00:00 [queued]>
[2023-12-03T00:07:30.902+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 3
[2023-12-03T00:07:30.919+0000] {taskinstance.py:1382} INFO - Executing <Task(S3ToRedshiftOperator): tsk_transfer_s3_to_redshift> on 2023-12-02 00:00:00+00:00
[2023-12-03T00:07:30.923+0000] {standard_task_runner.py:57} INFO - Started process 43250 to run task
[2023-12-03T00:07:30.927+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'zillow_analytics_dag', 'tsk_transfer_s3_to_redshift', 'scheduled__2023-12-02T00:00:00+00:00', '--job-id', '106', '--raw', '--subdir', '/home/ubuntu/airflow/dags', '--cfg-path', '/tmp/tmpmvcek7fi']
[2023-12-03T00:07:30.928+0000] {standard_task_runner.py:85} INFO - Job 106: Subtask tsk_transfer_s3_to_redshift
[2023-12-03T00:07:30.964+0000] {task_command.py:416} INFO - Running <TaskInstance: zillow_analytics_dag.tsk_transfer_s3_to_redshift scheduled__2023-12-02T00:00:00+00:00 [running]> on host ip-172-31-24-255.us-west-2.compute.internal
[2023-12-03T00:07:31.031+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='zillow_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_transfer_s3_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2023-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-02T00:00:00+00:00'
[2023-12-03T00:07:31.036+0000] {base.py:73} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2023-12-03T00:07:31.038+0000] {base.py:73} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2023-12-03T00:07:31.038+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2023-12-03T00:07:31.049+0000] {s3_to_redshift.py:192} INFO - Executing COPY command...
[2023-12-03T00:07:31.052+0000] {base.py:73} INFO - Using connection ID 'conn_id_redshift' for task execution.
[2023-12-03T00:09:41.321+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/redshift_connector/core.py", line 628, in __init__
    self._usock.connect(hostport)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 196, in execute
    redshift_hook.run(sql, autocommit=self.autocommit)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/redshift_sql.py", line 176, in get_conn
    return redshift_connector.connect(**conn_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/redshift_connector/__init__.py", line 376, in connect
    return Connection(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/redshift_connector/core.py", line 684, in __init__
    raise OperationalError("connection time out", timeout_error)
redshift_connector.error.OperationalError: ('connection time out', TimeoutError(110, 'Connection timed out'))
[2023-12-03T00:09:41.325+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=zillow_analytics_dag, task_id=tsk_transfer_s3_to_redshift, execution_date=20231202T000000, start_date=20231203T000730, end_date=20231203T000941
[2023-12-03T00:09:41.337+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 106 for task tsk_transfer_s3_to_redshift (('connection time out', TimeoutError(110, 'Connection timed out')); 43250)
[2023-12-03T00:09:41.369+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-03T00:09:41.378+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
