[2023-11-30T18:41:18.996+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_load_to_s3 manual__2023-11-30T18:40:38.433713+00:00 [queued]>
[2023-11-30T18:41:19.004+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_load_to_s3 manual__2023-11-30T18:40:38.433713+00:00 [queued]>
[2023-11-30T18:41:19.004+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 3
[2023-11-30T18:41:19.021+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): tsk_load_to_s3> on 2023-11-30 18:40:38.433713+00:00
[2023-11-30T18:41:19.025+0000] {standard_task_runner.py:57} INFO - Started process 31040 to run task
[2023-11-30T18:41:19.028+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'zillow_analytics_dag', 'tsk_load_to_s3', 'manual__2023-11-30T18:40:38.433713+00:00', '--job-id', '16', '--raw', '--subdir', '/home/ubuntu/airflow/dags', '--cfg-path', '/tmp/tmptsywo9tq']
[2023-11-30T18:41:19.030+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask tsk_load_to_s3
[2023-11-30T18:41:19.065+0000] {task_command.py:416} INFO - Running <TaskInstance: zillow_analytics_dag.tsk_load_to_s3 manual__2023-11-30T18:40:38.433713+00:00 [running]> on host ip-172-31-24-255.us-west-2.compute.internal
[2023-11-30T18:41:19.133+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='zillow_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_load_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-11-30T18:40:38.433713+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-30T18:40:38.433713+00:00'
[2023-11-30T18:41:19.134+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-30T18:41:19.135+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'aws s3 mv /home/ubuntu/response_data_30112023184041.json s3://sijiendtoendyoutube-bucket/']
[2023-11-30T18:41:19.142+0000] {subprocess.py:86} INFO - Output:
[2023-11-30T18:41:19.144+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: aws: command not found
[2023-11-30T18:41:19.144+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-11-30T18:41:19.151+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-11-30T18:41:19.154+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=zillow_analytics_dag, task_id=tsk_load_to_s3, execution_date=20231130T184038, start_date=20231130T184118, end_date=20231130T184119
[2023-11-30T18:41:19.167+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 16 for task tsk_load_to_s3 (Bash command failed. The command returned a non-zero exit code 127.; 31040)
[2023-11-30T18:41:19.200+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-30T18:41:19.213+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
